services:
    zookeeper:
      ports:
        - "2181:2181"

    broker:
      ports:
        - "9092:9092"
        - "9101:9101"

    clickhouse-node1:
      ports:
        - "8123:8123"
        - "9000:9000"

    ugc:
      volumes:
        - ./:/app/ugc_service
      command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
