version: '3.9'

services:
    redis:
      image: redis:7.0.11-alpine
      ports:
        - '6379:6379'
      volumes:
        - ugc_redis_volume:/data
      healthcheck:
        test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
        interval: 1s
        timeout: 3s
        retries: 5

volumes:
    ugc_redis_volume:
      name: ugc_redis_volume
